language: ruby
rvm:
- 2.2.3
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: kfjii6nOkPzshttKg8PDKGbb3v44614m/90mrSYOVwit0nBOE5n6NsNPpu0nHkQeHeFjYUQzxG3ZglhWAUiNKQJOE0GGSaIFAPqraHFs/463xUh3Jrdt/34AZG4H1I+rHaBGsLcIPmZyQ+Vi5k4RePU3uq33CX3jU8eYYdUQ0I90t8tsIiFS9M2yzmCpxC8rRPQ5Lq0uzmnOicbsud/EwTpfD7vaCg8MVFk3qLse4OGIBoC9F9ONruGX/qQ/5COqDb5lXThWOEggqmig7VUUN9Qk/X+zrxucclNz9zOdI4rM2xYEXcNcQMA4AeIa6rSCF23m/MnBTl8Prf0mYt58oorWSUq57w2zQzjlaq0KoRm6wgm65qmmLlzKOZFJL0Ev+nhbOzIesCHcN5hmNnhjzBBSRsk0AikBGpUsRxaP6dVhRSkfBHJ1d8w8nUUoTSeWV76z+q8GE60LnA38gLBtGFirW10MVOenU5UpTZB3jWrWLvw3TSiP86rjQeeKlSX47NGKpXiPhhgQrdYw/0T52NaYr66NyXnq8g5X/+amHZTcNtmXfK8bYR2vwFGJCdVH4wvUsJ7BL2VOswNTfxWuBN2Hk8BRoV8UBMExsRfuaUVD4Okeym2oS8Pc6+l568zGQftsfHhJMImZ6+wgUENYQfXg9UwtIEqetmu2QkAL+Pk=
  app: foodsters
  on:
    repo: zokuhara/foodsters
  run:
    - "rake db:migrate"
    - "rake cleanup"
