# Add configuration values here, as shown below.
#
yummly_app_id: "edbcfcd5"
yummly_key: "0d42cb9ca244e92e94111c5c10a59d9c"

stripe_secret_key: "sk_test_E3VVqeFWeRtGBe4jZX1n1od7"
stripe_publishable_key: "pk_test_tqSrylPqvVytJW2VxZz3bqBQ"
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
